docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v2
  versions:
    - v2
nav:
  - Home: index.md
  - v2:
      - Overview: v2/overview.md
      - Installation: v2/installation.md
      - Configuration: v2/configuration.md
      - Usage: v2/usage.md
site_name: dot-authentication
site_description: "Core interfaces for authentication implementations"
repo_url: "https://github.com/dotkernel/dot-authentication"
plugins:
  - search
